Django/myform/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),  # 빈 주소를 넣으면 http://127.0.0.1:8000/articles/
    path('new/', views.new, name='new'),  # /articles/new/
    path('<int:pk>/', views.detail, name='detail'),  # /articles/1/ or articles/2/
    path('<int:pk>/edit/', views.edit, name='edit'),  # /articles/edit/
    path('<int:pk>/like/', views.like, name='like'),
    path('search/', views.search, name='search'), # 검색페이지
]

Django/myform/myform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# def root(request):
#     return redirect('articles:index')

urlpatterns = [
    path('accounts/', include('accounts.urls')),  # accounts에서의 요청은 지금 이 urls.py가 아니라 accounts 안의 urls.py로 보내라
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('articles:index'), name='root'),  # 메인페이지에 어떤게 올지 정의할 수 있음
]

Django/myform/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 1:N (User:Article)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Article을 작성한 user -> Article.user
    # User가 작성한 모든 Article -> user.article_set.all() -> related_name 설정 안했을 때 ** <<코드중복>>
    # M:N [Like] - User:Article
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    # Article에 좋아요 누른 모든 user -> article.like.users.all()
    # User가 좋아요 누른 모든 Article -> user.article_set.all() -> related_name 설정 안했을 때 ** <<코드중복>>
    # 코드가 중복되기 때문에 related_name을 설정함
    # 설정 후 : user.article_set.all() -> user.like_articles.all()로 변경됨




# Auth
# 1. Authetication (인증)
# 2. Authorization (권한)

Django/myform/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):  # 특정한 모델을 위해 form을 작성
    class Meta:  # Class에 대한 정보가 담긴 Class
        model = Article
        fields = ['title', 'content', ]







# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class' : 'title', # class='title'
#                 'placeholder' : '제목을 입력하세요.', 
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class' : 'content',
#                 'rows' : 5,
#                 'cols' : 20,
#                 'placeholder' : '내용을 입력하세요.',

#             }
#         )
#     )






# Form Class의 용도
# 1. Form tag 만들기
# 2. 데이터베이스에 데이터 생성하기

Django/myform/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    article_list = Article.objects.all()
    # Paginator
    # 1. articles를 Paginator에 입력
    paginator = Paginator(article_list, 3)
    # 2. 몇번째 page를 보여줄건지 GET으로 가져옴
    page = request.GET.get('page')
    # 3. 해당하는 page의 articles만 뽑기
    articles = paginator.get_page(page)
    # 4. 총 page 수를 range로 변환
    # num_pages = range(1, articles.paginator.num_pages() + 1)

    context = {
        'articles' : articles,
        # 'num_pages' : num_pages,
    }
    return render(request, 'articles/index.html', context)  # articles-templates-articles-index.html


# Form 사용
# def new(request):
#     if request.method == 'POST':
#         # 데이터베이스에 데이터 생성
#         # 1. 넘어온 데이터를 받기
#         article_form = ArticleForm(request.POST)
#         # title = request.POST.get('title')
#         # content = request.POST.get('content')
#         # 2. 넘어온 데이터 검증
#         if article_form.is_valid():  # 데이터가 유효한지 검증
#             title = article_form.cleaned_data.get('title')
#             content = article_form.cleaned_data.get('content')
#             # 3. 데이터베이스에 article 만들기
#             article = Article.objects.create(title=title, content=content)
#             # 4. redirect -> detail (detail->상세 페이지 보여주기, 동적으로 바뀌는 페이지, pk에 바뀌는 페이지에 대한 숫자 넣어주기)
#             return redirect('articles:detail', article.pk)  # redirect 함수 추가해야함
#     else:
#         article_form = ArticleForm()
#         # 폼을 보여줌
#         context = {
#             'article_form' : article_form,
#         }
#         return render(request, 'articles/new.html', context)



@login_required # 로그인이 안되어있어도 주소를 입력하면 articles/new 페이지로 직접 갈 수 있는데 이거 못가게 막는 것 
# ModelForm 사용
def new(request):
    if request.method == 'POST':
        # 데이터베이스에 데이터 생성
        # 1. 넘어온 데이터를 받기
        article_form = ArticleForm(request.POST)
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        # 2. 넘어온 데이터 검증
        if article_form.is_valid():  # 데이터가 유효한지 검증
            # 3. 데이터베이스에 article 만들기
            article = article_form.save(commit=False)  # form 사용했을 때 if문 안쪽의 3줄의 코드가 -> modelform을 사용하면 한줄로 줄어든다.
            # 3-1. user 정보 끼워넣기
            article.user = request.user
            article.save()
            # 4. redirect -> detail (detail->상세 페이지 보여주기, 동적으로 바뀌는 페이지, pk에 바뀌는 페이지에 대한 숫자 넣어주기)
            return redirect('articles:detail', article.pk)  # redirect 함수 추가해야함
    else:
        article_form = ArticleForm()
    # 폼을 보여줌 : else에서 빼줌 -> is_valid가 성립하지 않을때 보여줄 수 있음. 문법적인 오류 발생안함.
    # 화면에서 F12 눌러서 네모칸(타이틀, 텍스트 입력하는 칸)에 가서 'required id = ~~ ' 이 부분을 삭제하고, 빈칸으로 제출을 누르면
    # 이 입력란을 작성하라고 뜨거나 필수항목이라고 뜬다 (유효성 검증)
    context = {
        'article_form' : article_form,
    }
    return render(request, 'articles/new.html', context)


def detail(request, pk):
    # 1. pk번째 데이터를 가져오기
    article = Article.objects.get(pk=pk)
    # 2. context로 넘겨주기
    context = {
        'article' : article,
    }
    # 3. render와 함께 넘겨주기
    return render(request, 'articles/detail.html', context) 


# form 사용
# def edit(request, pk):
#     article = Article.objects.get(pk=pk)  # 수정하고자 하는 게시물의 정보가 들어있음
#     if request.method == 'POST':
#         # article 수정
#         # 1. 넘어온 데이터 받기
#         article_form = ArticleForm(request.POST)
#         # 2. 데이터 검증
#         if article_form.is_valid():
#             article.title = article_form.cleaned_data.get('title')
#             article.content = article_form.cleaned_data.get('content')
#             article.save()
#             # 4. redirect -> detail
#             return redirect('articles:detail', article.pk)
#     else:
#         # article 수정하는 form 보여주기(=render)
#         article_form = ArticleForm(
#             {
#                 'title' : article.title,
#                 'content' : article.content,
#             }
#         )
#         context = {
#             'article_form' : article_form,
#         }
#         return render(request, 'articles/new.html', context)


@login_required
# MdelForm 사용
def edit(request, pk):
    article = Article.objects.get(pk=pk)  # 수정하고자 하는 게시물의 정보가 들어있음
    # article의 주인인지 검증
    if request.user != article.user:
        return redirect('articles:index')
    
    if request.method == 'POST':
        # article 수정
        # 1. 넘어온 데이터 받기 
        article_form = ArticleForm(request.POST, instance=article)  # 인스턴스를 넘겨주면서 데이터 받을 때 수정도 같이 해버림
        # 2. 데이터 검증
        if article_form.is_valid():
            # 3. 검증된 데이터로 수정 & 저장
            article_form.save()  # 수정한거를 저장(실제 수정은 1번에서 수정)
            # 4. redirect -> detail
            return redirect('articles:detail', article.pk)
    else:
        # article 수정하는 form 보여주기(=render)
        article_form = ArticleForm(instance=article)  # pk로 가져온 하나의 게시물을 인스턴스에 넣어준다
    context = {
        'article_form' : article_form,
    }
    return render(request, 'articles/new.html', context)


# POST 요청만 받음
@login_required
def like(request, pk):
    # 1. pk번 article을 가져오기
    article = Article.objects.get(pk=pk)
    # 2. 현재 로그인한 user가 이 article에 좋아요를 눌렀는지 판별
    if request.user in article.like_users.all():
        # 3-1. 좋아요 취소
        article.like_users.remove(request.user)
    else:    
        # 3-2. 좋아요
        article.like_users.add(request.user)

    return redirect('articles:detail', pk)


# GET 요청을 받음, 검색페이지
def search(request):
    # 1. request로부터 검색어 가져오기
    query = request.GET.get('query') # -> asdf
    # 2. article에서 제목에 검색어가 있는지 찾기
    articles = Article.objects.filter(title__contains=query)  # title에 이 query가 있는 친구들만 가져와
    # title__contains : 대소문자 구분 안함(A 입력해도 a 나와영)
    # title__icontains : 대소문자 구분 해서 검색(A 입력하면 A만 나옴) -> 근데 지금은 안됨...
    # 고급 검색기능을 하고 싶으면 별도의 검색 엔진을 사용해야하는데, solr(솔라) 대표적 -> 이런건 검색엔진 서버를 따로 돌려야함(장고 서버 돌리고 검색엔진도 서버 돌리고..)
    # but 기본적인 간단한 기능은 장고에 다 있음..!!!
    # 3. context로 결과값 template에 넘겨주기
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/search.html', context)

Django/myform/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Detail</h1>

<p>pk : {{ article.pk }}</p>
<p>user : {{ article.user.username }}</p>
<p>title : {{ article.title }}</p>
<p>content : {{ article.content }}</p>
<p>created at : {{ article.created_at }}</p>
<p>updated at : {{ article.updated_at }}</p>

<p>like: {{ article.like_users.count }}</p>

{% if user.is_authenticated %}
<form action="{% url 'articles:like' article.pk %}", method="POST">
    {% csrf_token %}
    {% if user in article.like_users.all %}
    <input type="submit" value="좋아요 취소" >
    {% else %}
    <input type="submit" value="좋아요">
    {% endif %}
</form>
{% endif %}

<div>
    <a href="{% url 'articles:index' %}">List</a>
    {% if user == article.user %}
    <a href="{% url 'articles:edit' article.pk %}">Edit</a>
    {% endif %}
</div>


{% endblock %}

Django/myform/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}

<form action="{% url 'articles:search' %}" method="GET"> <!-- method를 별도로 지정하지 않으면 기본적으로 GET, 명시 한번 해봤음-->
    <input type="text" name="query">
    <input type="submit" value="제목으로 검색">
</form>

<h1>Article Index</h1>

{% if user.is_authenticated %}
<a href="{% url 'articles:new' %}">New Article</a>
{% endif %}

<ul>
    {% for article in articles %}
    <li> 
        <a href="{% url 'articles:detail' article.pk %}">
            {{ article.title }} 
        </a>
    </li>
    {% endfor %}
</ul>

<!-- Bootstrap Pagination -->
<nav>
    <ul class="pagination">
        {% if articles.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.previous_page_number }}">Previous</a>
        </li>
        {% endif %}

        {% for num_page in articles.paginator.page_range %}
        <li class="page-item {% if num_page == articles.number %}active{% endif %}">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ num_page }}">{{ num_page }}</a>
        </li>
        {% endfor %}
        <!-- <li class="page-item">
            <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="#">3</a>
        </li> -->

        {% if articles.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.next_page_number }}">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

Django/myform/articles/templates/articles/new.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h1>Article Form</h1>

<form action="", method="POST"> <!-- action에 주소 안넣으면 자기 자신에게 반환 -->
    {% csrf_token %}
    <!-- <label for="">Title</label>
    <input type="text", name='title'>
    <label for="">Content</label>
    <textarea name="content" id="" cols="30" rows="10"></textarea> -->
    <!-- {{ article_form.as_p }} -->
    {% bootstrap_form article_form %}  <!-- 폼을 예쁘고 깔끔하게 변경 -->
    {% buttons submit='작성하기' %} <!-- 버튼 예쁘게 변경 -->
        <!-- 추가 버튼 생성 가능 -->
    {% endbuttons %}
    <!-- <input type="submit"> -->

</form>

{% endblock %}

Django/myform/articles/templates/articles/search.html
{% extends 'base.html' %}

{% block body %}

<h1>Search Result</h1>

<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'articles:detail' article.pk %}">
            {{ article.title }}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}