Django/crud_review/crud_review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('students/', include('students.urls')),
    path('admin/', admin.site.urls),
    
]

Django/crud_review/students/urls.py
'''
원래 urls.py에서 틀 가져오기
from django.urls import path

urlpatterns = [
   
]
'''


from django.urls import path
from . import views  # 같은 폴더에서 views를 import 해와라

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'),  # GET /students/
    path('new/', views.new, name='new'),  # views가 없으니까 위에 임포트 해죠야해  # GET /students/new/
    # new + create 하려고 create 없앰  # GET,POST /students/new/
    #path('create/', views.create, name='create'),  # POST /students/create/
    path('<int:pk>/', views.detail, name='detail'),  # GET /students/1/
    path('<int:pk>/edit/', views.edit, name='edit'),  # 뭐를 수정할지 알려줘야 하니까 <int:pk>/를 같이 넣어야해  # GET students/1/edit/
    # edit + update  # GET,POST students/1/edit/
    #path('<int:pk>/update/', views.update, name='update'),  # GET /students/1/update/ (x)
    path('<int:pk>/delete/', views.delete, name='delete'),  # GET /students/1/delete/ (x)

]

#
# 😀URL Name -> 각각의 패스에 적용

# path('주소/', views.함수, name='이름')
# django templates language : {{ }} or {% %}
# {% url '이름' %} => 주소로 바로 변환
# ex) {% url 'new' %} => /students/new/  # index.html 페이지에서 사용

# [장점]
# 1. 주소의 변경이 필요할 때, urls.py에서만 수정해주면 됨
#   - urls.py는 url 주소를 관리하는 페이지인데 name을 사용하지 않고 링크 입력하는 방법으로 사용하면
#   - 주소가 변경될 때 이 주소가 변경되는 html을 모두 찾아서 수정해야하는 번거로움이 있음
# 2. 마지막 '/'를 빼먹는 실수를 차단 가능

# App Name -> 특정 app의 urls.py에 적용
# {% url '앱이름:패스이름' %} = {% url 'app_name:path_name' %}
# {% url 'students:index' %}


#
# 😀RESTful
# 1. 자원(Resource) - URI
# 2. 행위(Verb) - http method (GET, POST, ...)
# 3. 표현(Representations) = 자원 + 행위
# 예)
# GET/users/read/1 (x)  -> read 같이 주소 안에 행위가 들어가면 restful한 주소가 아님
# GET/users/1 (o)

# restful 기본
# 1) 슬래시(/)는 개층 관계를 나타내는데 사용
# 2) 소문자 사용
# 3) 파일 확장자는 포함 안함
# 4) 밑줄(_) 대신 하이픈(-) 사용
# 5) 주소 마지막에 슬래시(/)를 포함하지 않음 -> django는 끝에 필수로 포함해야 하는 경우도 있어서 헷갈림


# Django는 PUT/PATCH/DELETE 불가능, 따라서..
# GET  /studetns/2/edit  #=> 수정 페이지 보여줌
# POST /students/2/edit  #=> 수정 작업 수행
# ex)
# GET    /users/1  #=> user 1번 가져옴
# PUT    /users/1  #=> user 1번 수정
# DELETE /users/1  #=> user 1번 삭제

Django/crud_review/students/models.py
from django.db import models

# 파이썬 코드라서 데이터베이스가 알아듣지를 못해
# 그래서 알아들을 수 있게 변환해주는거 -> makemigration -> 0001_initial.py 생성
# 데이터베이스 들어가기 직전 파일

# Create your models here.
class Student(models.Model):  # Student에 대한 설계도, class 이름은 대문자로 시작하기
    #id = models.AutoField(primary_key=True)  # id값 따로 설정 안해줘도 괜찮음
    name = models.CharField(max_length=10)
    age = models.IntegerField()  # 숫자만 기록
    created_at = models.DateTimeField(auto_now_add=True)  # 새로운 데이터가 생성될때만 기록
    updated_at = models.DateTimeField(auto_now=True)  # 생성 혹은 수정 등 변경될때 기록
    
    # 1. DB에 테이블을 생성하기 위한 설계도 생성 
    # python manage.py makemigrations
    # 에러가 나면 저장이 잘 되어있는지, settings.py에 INSTALLED_APPS에 추가가 잘 되어는지 확인
    #
    # 2. 위의 설계도를 가지고 실제 DB에 테이블을 생성
    # python manage.py migrate 




# Articles
#
# id, created_at은 데이타베이스에 저장이 되어야 생기는 것

# 
# 1. models.py에 원하는 class 작성
# 2. python manage.py makemigrations
#    -> medels.py를 바탕으로 설계도(migration 파일) 생성
# 3. python manage.py migrate
#    -> DB(db, sqlite3)에 설계도를 적용(테이블 생성)
#


# DB에 데이터를 생성하는 방법 3가지
# 1. article = Article()
#    article.title = '제목'
#    article.content = '내용'
#    article.save()
#
# 2. article = Article(title='두번째', content='두번째 내용')
#    article.save()
#
# 3. article = Article.objects.create(title='세번째', content='세번째 내용')


# Read
# 1. All - Article.objects.all()  # 복수(QuerySet), 데이터베이스 모두 불러올 수 있음
#
# 2. 1개 - Article.objects.get(id=1)  # 단수(인스턴스), get은 무조건 하나만 나옴, 조건을 주고 검색
#          Article.objects.get(title='세번째')  # title 같은게 여러개이면 에러발생
#          # unique한 컬럼으로 가져오는게 좋음! => id!! get은 id랑 쓰기
#          # 결과가 0이어도 에러 발생, 오직 1개만 가능
#
# 3. 조건 - Article.objects.filter(title='세번째')  # 복수가능, where랑 비슷
#
# 4. QuerySet + .first(), last()  # 단수
#    Article.objects.filter(title='세번째').first()  # 조건이 맞는 결과값 중에서 첫번째꺼 출력
#    Article.objects.filter(title='세번째').last()  # 조건이 맞는 결과값 중에서 마지막꺼 출력
#
# 4-1. Article.objects.filter(title='안녕')                                   
#      Out[16]: <QuerySet []>  # 조건에 맞는 결과가 없을 때 filter는 에러가 아니라 빈값을 출력
# 4-2. order_by(컬럼명)
#      Article.objects.all().order_by('title')  # title 기준으로 오름차순 정렬
#      Article.objects.all().order_by('-title')  # - 붙이면 내림차순 정렬
# 4-3. offset, limit (OFFSET, LIMIT) [offset:offset+limit]
#      Article.objects.all()[1:3]  # => [2,3]


# Update
# 1. 데이터 가져오기 
#    a = Article.objects.get(id=1)  
#    a.title  # '첫번째 글 입니다.'
# 2. 수정할 값 할당하기 
#    a.title = 'First!' 
#    a.title  # 'First!'
# 3. 저장하기(DB에 반영)
#    a.save()


# Delete    
# 1. 데이터 가져오기
#    a = Article.objects.get(id=1)
#    a  # <Article: 1번 글 - First! : 내용입니다.>
# 2. 데이터 삭제하기(DB에 반영)
#    a.delete()
#    a  # <Article: None번 글 - First! : 내용입니다.> # 호출하면 id 없음
#    Article.objects.all()  # DB 불러보면 id=1 없음                                          
#    # => <QuerySet [<Article: 2번 글 - 두번째 : 두번째 내용>, <Article: 3번 글 - 세번째 : 세번째 내용>, <Article: 4번 글 - 세번째 : 세번째 내용2>]>

Django/crud_review/students/views.py
from django.shortcuts import render, redirect
from .models import Student

# Create your views here.
def index(request):
    # 1. 모든 students를 DB에서 가져오기
    students = Student.objects.all()

    # 2. context에 저장
    context = {
        'students' : students,
    }

    # 3. render하면서 context 넘겨주기
    return render(request, 'students/index.html', context)


def new(request):
    if request.method == 'POST': # 'GET', 'POST'
        # student를 생성함
        # 1. POST 요청으로 넘어온 데이터 가져오기(name, age)
        name = request.POST.get('name')  # new.html에서 input의 속성 중 name의 값을 입력
        age = request.POST.get('age')

        # 2. Model 클래스 사용해서 DB에 저장
        # from .models import Student 해주기
        student = Student(name=name, age=age)
        student.save()

        # 3. 생성된 학생의 상세 정보를 보는 페이지로 이동(Detail)
        #return redirect(f'/students/{student.pk}/')  # 렌더를 하지 않기 때문에 html 파일 생성안해도 됨
        return redirect('students:detail', student.pk)
    else:
        # new page를 보여주면 됨(def new)
        return render(request, 'students/new.html')
    #return render(request, 'students/new.html')

'''
# POST 요청을 받는 친구, 생성하는 역할만 하고 보여주는건 다른 애가 함
def create(request):
    # 1. POST 요청으로 넘어온 데이터 가져오기(name, age)
    name = request.POST.get('name')  # new.html에서 input의 속성 중 name의 값을 입력
    age = request.POST.get('age')

    # 2. Model 클래스 사용해서 DB에 저장
    # from .models import Student 해주기
    student = Student(name=name, age=age)
    student.save()

    # 3. 생성된 학생의 상세 정보를 보는 페이지로 이동(Detail)
    #return redirect(f'/students/{student.pk}/')  # 렌더를 하지 않기 때문에 html 파일 생성안해도 됨
    return redirect('students:detail', student.pk)
'''

def detail(request, pk):
    # 1. pk에 해당하는 student를 DB에서 가져오기
    student = Student.objects.get(pk=pk)  # student 인스턴스 반환
    
    # 2. context에 저장
    context = {
        'student' : student,
    }

    # 3. render 하면서 context 넘겨주기
    return render(request, 'students/detail.html', context)
    

def edit(request, pk):
    # 1. pk에 해당하는 학생 DB에서 가져오기
    student = Student.objects.get(pk=pk)
    if request.method == 'POST':
        # student를 수정(def update)
        # 2. POST 요청을 통해 넘어온 데이터 가져오기
        name = request.POST.get('name')
        age = request.POST.get('age')

        # 3. student 인스턴스의 정보를 변경 & DB에 반영
        student.name = name
        student.age = age
        student.save()

        # 4. student 상세 페이지로 이동해서 변경내용 확인(Detail)
        #return redirect(f'/students/{student.pk}')
        return redirect('students:detail', student.pk)
    else:
        # 수정하는 페이지를 보여줌(def edit)
        # 2. context에 저장
        context = {
            'student' : student,
        }

        # 3. render 하면서 context에 넘겨주기
        return render(request, 'students/edit.html', context)

'''
# POST 요청만 받음
def update(request, pk):
    # 1. pk에 해당하는 student를 DB에서 가져오기
    student = Student.objects.get(pk=pk)

    # 2. POST 요청을 통해 넘어온 데이터 가져오기
    name = request.POST.get('name')
    age = request.POST.get('age')

    # 3. student 인스턴스의 정보를 변경 & DB에 반영
    student.name = name
    student.age = age
    student.save()

    # 4. student 상세 페이지로 이동해서 변경내용 확인(Detail)
    #return redirect(f'/students/{student.pk}')
    return redirect('students:detail', student.pk)
'''
# POST 요청만을 받음 -> redirect()
def delete(request, pk):
    if request.method == 'POST':
        # 1. pk에 해당하는 student를 DB에서 가져오기
        student = Student.objects.get(pk=pk)
        
        # 2. student 삭제(DB에서 삭제하기)
        student.delete()

        # 3. index 페이지로 이동
        #return redirect('/students/')
        return redirect('students:index')
    
    # return 없음! 오류!

Django/crud_review/crud_review/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

Django/crud_review/students/templates/students/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Student Detail</h1>

<h3>{{ student.name }}</h3>
<h4>{{ student.age }}</h4>
<h5>{{ student.created_at }}</h5>
<h5>{{ student.updated_at }}</h5>
<!-- 
<a href="/students/">List</a>

<a href="/students/{{ student.pk }}/edit/">Edit</a>

<a href="/students/{{ student.pk }}/delete/">Delete</a>
-->
<a href="{% url 'students:index' %}">List</a>

<a href="{% url 'students:edit' student.pk %}">Edit</a>

<!-- a tag는 POST 요청을 보낼 수 없습니다. 그렇다면..? from tag! -->
<!-- <a href="{% url 'students:delete' student.pk %}">Delete</a> -->
<form action="{% url 'students:delete' student.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock %}

Django/crud_review/students/templates/students/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Edit student</h1>

<!-- <form action="/students/{{ student.pk }}/update/" method="POST"> --> <!-- pk값을 받아서 수정해서 update로 요청보내기 -->
<!-- <form action="{% url 'students:update' student.pk %}" method="POST"> -->
<form action="" method="POST">
    {% csrf_token %}
    <label for="">Name</label>
    <input type="text", name="name", value="{{ student.name }}">
    <label for="">Age</label>
    <input type="number", name="age", value="{{ student.age }}">
    <input type="submit">
</form>

{% endblock %}

Django/crud_review/students/templates/students/index.html
{% extends 'base.html' %}

{% block body %}

<h1>Student Index</h1>

<!-- <a href="/students/new/">New</a> -->
<a href="{% url 'students:new' %}">New</a>
<ul>
    {% for student in students %}
        <li>
            <!-- <a href="/students/{{ student.pk }}/">{{ student.name }}</a> -->
            <a href="{% url 'students:detail' student.pk %}">{{ student.name }}</a>
            <!-- url 함수의 첫번째 파라미터가 detail, 두번째가 student.pk -->
            
        </li>
    {% endfor %}
</ul>

{% endblock %}

Django/crud_review/students/templates/students/new.html
{% extends 'base.html' %}

{% block body %}

<h1>New Student</h1>

<!-- <form action="/students/create/" method="POST"> -->
<!-- <form action="{% url 'students:create' %}" method="POST"> -->
<form action="" method="POST">  <!-- action에 아무것도 안넣으면 자기 자신한테 요청보냄 -->
    {% csrf_token %}
    <label for="">Name</label>
    <input type="text", name="name">
    <label for="">Age</label>
    <input type="number", name="age">
    <input type="submit">
</form>

{% endblock %}